UvaFit/Controllers/GerenciarMatriculaController.cs
using Microsoft.AspNetCore.Mvc;
using UvaFit.Models;
using UvaFit.Repositorio;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace UvaFit.Controllers
{
    public class GerenciarMatriculaController : Controller
    {

        private readonly IMatriculaRepositorio _matriculaRepositorio;


        public GerenciarMatriculaController(IMatriculaRepositorio matriculaRepositorio)
        {
            _matriculaRepositorio = matriculaRepositorio;
        }
        public IActionResult Index()
        {
            List<MatriculaModel> matriculas = _matriculaRepositorio.BuscarTodas();
            return View(matriculas);
        }

        public IActionResult Adicionar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            MatriculaModel matricula = _matriculaRepositorio.BuscarPorId(id);
            return View(matricula);
        }

        public IActionResult DeletarConfirmacao(int id)
        {
            MatriculaModel matricula = _matriculaRepositorio.BuscarPorId(id);
            return View(matricula);
        }

        public IActionResult Deletar(int id)
        {
            try
            {
                bool deletado = _matriculaRepositorio.Remover(id);

                if (deletado)
                {
                    TempData["MensagemSucesso"] = "Matrícula deletada com sucesso";
                }
                else
                {
                    TempData["MensagemErro"] = "Não foi possível deletar a matrícula";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {

                TempData["MensagemErro"] = $"Não foi possível deletar a matrícula! Detalhe do erro: {erro.Message} ";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Adicionar(MatriculaModel matricula)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _matriculaRepositorio.Adicionar(matricula);
                    TempData["MensagemSucesso"] = "Matrícula adicionada com sucesso";
                    return RedirectToAction("Index");

                }

                return View(matricula);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Não foi possível adicionar a matrícula! Detalhe do erro: {erro.Message} ";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Editar(MatriculaModel matricula)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _matriculaRepositorio.Atualizar(matricula);
                    TempData["MensagemSucesso"] = "Matricula editada com sucesso";
                    return RedirectToAction("Index");

                }

                return View(matricula);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Não foi possível editar a matrícula! Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

UvaFit/Controllers/TelaFuncionarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace UvaFit.Controllers
{
    public class TelaFuncionarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

UvaFit/Views/GerenciarMatricula/DeletarConfirmacao.cshtml
@model MatriculaModel
@{
    ViewData["Title"] = "Deletar Matrícula";
}

<div class="text-center">
    <h3>Deseja realmente deletar o aluno(@Model.Nome )?</h3>
</div>

<div class="text-center">
    <a class="btn btn-success" role="button" asp-controller="GerenciarMatricula" asp-action="Index">Cancelar</a>
    <a class="btn btn-danger" role="button" asp-controller="GerenciarMatricula" asp-action="Deletar" asp-route-id="@Model.Id">Confirmar</a>
</div>

UvaFit/Views/GerenciarMatricula/Editar.cshtml
@using UvaFit.Enums
@model MatriculaModel
@{
    ViewData["Title"] = "Editar Matrícula";
}

<div class="text-center">


    <h1>Editar Matrícula</h1>

</div>

<form asp-controller="GerenciarMatricula" asp-action="Editar" method="post">

    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do aluno">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="CPF">CPF</label>
        <input type="text" asp-for="CPF" class="form-control" placeholder="Digite o CPF do aluno">
        @Html.ValidationMessageFor(x => x.CPF)
    </div>

    <div class="form-group">
        <label for="E-mail">E-mail</label>
        <input type="email" asp-for="Email" class="form-control" placeholder="Digite o e-mail do aluno">
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="DataCadastro">Data de matriculação</label>
        <input type="date" asp-for="DataCadastro" class="form-control" placeholder="Informe a data de matriculação do aluno">
        @Html.ValidationMessageFor(x => x.DataCadastro)
    </div>

    <div class="form-group">
        <label for="DataPagamento">Data de pagamento</label>
        <input type="date" asp-for="DataPagamento" class="form-control" placeholder="Informe a data de pagamento do aluno">
        @Html.ValidationMessageFor(x => x.DataPagamento)
    </div>

    <div class="form-group">
        <label for="PlanoMatriculaEnum">Plano</label>
        <select asp-for="PlanoMatricula" class="form-control">
            <option value="0">Selecione</option>
            <option value="@PlanoMatriculaEnum.Anual">Anual</option>
            <option value="@PlanoMatriculaEnum.Mensal">Mensal</option>
            <option value="@PlanoMatriculaEnum.Avulso">Avulso</option>

        </select>

    </div>

    <br />

    <button type="submit" class="btn btn-success">Alterar</button>
    <a class="btn btn-secondary" asp-controller="GerenciarMatricula" asp-action="Index" role="button">Voltar</a>

</form>

<style>
    .field-validation-error {
        color: #e01d1d;
    }
</style>

UvaFit/Views/GerenciarMatricula/Index.cshtml
@model List<MatriculaModel>
@{
    ViewData["Title"] = "Gerenciar Matrícula";
}

<div class="text-center">

    <div class="d-flex justify-content-between">

        <a class="btn btn-danger" role="button" asp-controller="TelaFuncionario" asp-action="Index">Voltar</a>
    </div>

    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"];
        </div>
    }


    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemErro"];
        </div>
    }

    <h1>Listagem de Matrículas</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">CPF</th>
                <th scope="col">E-mail</th>
                <th scope="col">Data de matriculação</th>
                <th scope="col">Data de pagamento</th>
                <th scope="col">Plano</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (MatriculaModel matricula in Model)
                {
                    <tr>
                        <th scope="row">@matricula.Id</th>
                        <td>@matricula.Nome</td>
                        <td>@matricula.CPF</td>
                        <td>@matricula.Email</td>
                        <td>@matricula.DataCadastro</td>
                        <td>@matricula.DataPagamento</td>
                        <td>@matricula.PlanoMatricula</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-danger" asp-route-id="@matricula.Id" asp-controller="GerenciarMatricula" asp-action="DeletarConfirmacao">Deletar</a>
                                <a role="button" class="btn btn-warning" asp-route-id="@matricula.Id" asp-controller="GerenciarMatricula" asp-action="Editar">Editar</a>
                            </div>
                        </td>
                    </tr>

                }

            }
        </tbody>
    </table>

</div>

<style>
    .close-alert {
        position: absolute;
        right: -10px;
        top: -15px;
        border-radius: 15px;
        width: 30px;
        height: 31px;
    }
</style>