UvaFit/Controllers/GerenciarEquipamentoController.cs
using Microsoft.AspNetCore.Mvc;
using UvaFit.Models;
using UvaFit.Repositorio;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace UvaFit.Controllers
{
    public class GerenciarEquipamentoController : Controller
    {

        private readonly IEquipamentoRepositorio _equipamentoRepositorio;


        public GerenciarEquipamentoController(IEquipamentoRepositorio equipamentoRepositorio)
        {
            _equipamentoRepositorio = equipamentoRepositorio;
        }
        public IActionResult Index()
        {
            List<EquipamentoModel> equipamentos = _equipamentoRepositorio.BuscarTodos();
            return View(equipamentos);
        }

        public IActionResult EquipamentoAlunoIndex()
        {
            List<EquipamentoModel> equipamentos = _equipamentoRepositorio.BuscarTodos();
            return View(equipamentos);
        }

        public IActionResult Adicionar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            EquipamentoModel equipamento = _equipamentoRepositorio.ListarPorId(id);
            return View(equipamento);
        }

        public IActionResult DeletarConfirmacao(int id)
        {
            EquipamentoModel equipamento = _equipamentoRepositorio.ListarPorId(id);
            return View(equipamento);
        }

        public IActionResult Deletar(int id)
        {
            try
            {
                bool deletado = _equipamentoRepositorio.Deletar(id);

                if (deletado)
                {
                    TempData["MensagemSucesso"] = "Equipamento deletado com sucesso";
                }
                else
                {
                    TempData["MensagemErro"] = "Não foi possível deletar o equipamento";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {

                TempData["MensagemErro"] = $"Não foi possível apagar o equipamento ! Detalhe do erro: {erro.Message} ";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Adicionar(EquipamentoModel equipamento)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _equipamentoRepositorio.Adicionar(equipamento);
                    TempData["MensagemSucesso"] = "Equipamento adicionado com sucesso";
                    return RedirectToAction("Index");

                }

                return View(equipamento);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Não foi possível adicionar o equipamento! Detalhe do erro: {erro.Message} ";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Editar(EquipamentoModel equipamento)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _equipamentoRepositorio.Atualizar(equipamento);
                    TempData["MensagemSucesso"] = "Equipamento editado com sucesso";
                    return RedirectToAction("Index");

                }

                return View(equipamento);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Não foi possível editar o equipamento! Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

UvaFit/Controllers/TelaAlunoController.cs
using Microsoft.AspNetCore.Mvc;

namespace UvaFit.Controllers
{
    public class TelaAlunoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Visualizar()
        {
            return View();
        }

        public IActionResult Treino()
        {
            return View();
        }
    }
}

UvaFit/Controllers/TelaFuncionarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace UvaFit.Controllers
{
    public class TelaFuncionarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

UvaFit/Views/GerenciarEquipamento/Adicionar.cshtml
@using UvaFit.Enums
@model EquipamentoModel
@{
    ViewData["Title"] = "Adicionar Equipamento";
}

<div class="text-center">


    <h1>Adicionar Equipamento</h1>

</div>

<form asp-controller="GerenciarEquipamento" asp-action="Adicionar" method="post">
    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do equipamento">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="Status">Status</label>
        <select asp-for="SituacaoEquipamento" class="form-control">
            <option value="0">Selecione</option>
            <option value="@SituacaoEquipamentoEnum.Funcionando">Funcionando</option>
            <option value="@SituacaoEquipamentoEnum.Manutencao">Manutenção</option>

        </select>

    </div>

    <br />

    <button type="submit" class="btn btn-success">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="GerenciarEquipamento" asp-action="Index" role="button">Voltar</a>

</form>

<style>
    .field-validation-error {
        color: #e01d1d;
    }
</style>

UvaFit/Views/GerenciarEquipamento/DeletarConfirmacao.cshtml
@model EquipamentoModel
@{
    ViewData["Title"] = "Deletar Equipamento";
}

<div class="text-center">
    <h3>Deseja realmente deletar o equipamento(@Model.Nome )?</h3>
</div>

<div class="text-center">
    <a class="btn btn-success" role="button" asp-controller="GerenciarEquipamento" asp-action="Index">Cancelar</a>
    <a class="btn btn-danger" role="button" asp-controller="GerenciarEquipamento" asp-action="Deletar" asp-route-id="@Model.Id">Confirmar</a>
</div>

UvaFit/Views/GerenciarEquipamento/Editar.cshtml
@using UvaFit.Enums
@model EquipamentoModel
@{
    ViewData["Title"] = "Editar Equipamento";
}

<div class="text-center">


    <h1>Editar Equipamento</h1>

</div>

<form asp-controller="GerenciarEquipamento" asp-action="Editar" method="post">

    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do equipamento">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="Status">Status</label>
        <select asp-for="SituacaoEquipamento" class="form-control">
            <option value="0">Selecione</option>
            <option value="@SituacaoEquipamentoEnum.Funcionando">Funcionando</option>
            <option value="@SituacaoEquipamentoEnum.Manutencao">Manutenção</option>

        </select>

    </div>

    <br />

    <button type="submit" class="btn btn-success">Alterar</button>
    <a class="btn btn-secondary" asp-controller="GerenciarEquipamento" asp-action="Index" role="button">Voltar</a>

</form>

<style>
    .field-validation-error {
        color: #e01d1d;
    }
</style>

UvaFit/Views/GerenciarEquipamento/EquipamentoAlunoIndex.cshtml
@model List<EquipamentoModel>
@{
    ViewData["Title"] = "Visualizar Equipamento";
}

<div class="text-center">

    <div class="d-flex justify-content-between">
        <a class="btn btn-danger" role="button" asp-controller="TelaAluno" asp-action="Index">Voltar</a>
    </div>

    <br />


    <h1>Listagem de Equipamentos</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (EquipamentoModel equipamento in Model)
                {
                    <tr>
                        <th scope="row">@equipamento.Id</th>
                        <td>@equipamento.Nome</td>
                        <td>@equipamento.SituacaoEquipamento</td>
                        <td>
                        </td>
                    </tr>

                }

            }
        </tbody>
    </table>

</div>

<style>
    .close-alert {
        position: absolute;
        right: -10px;
        top: -15px;
        border-radius: 15px;
        width: 30px;
        height: 31px;
    }
</style>

UvaFit/Views/GerenciarEquipamento/Index.cshtml
@model List<EquipamentoModel>
@{
    ViewData["Title"] = "Gerenciar Equipamento";
}

<div class="text-center">

    <div class="d-flex justify-content-between">
        <a class="btn btn-success" role="button" asp-controller="GerenciarEquipamento" asp-action="Adicionar">Adicionar novo equipamento</a>
        <a class="btn btn-danger" role="button" asp-controller="TelaFuncionario" asp-action="Index">Voltar</a>
    </div>

    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"];
        </div>
    }


    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemErro"];
        </div>
    }

    <h1>Listagem de Equipamentos</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (EquipamentoModel equipamento in Model)
                {
                    <tr>
                        <th scope="row">@equipamento.Id</th>
                        <td>@equipamento.Nome</td>
                        <td>@equipamento.SituacaoEquipamento</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-danger" asp-route-id="@equipamento.Id" asp-controller="GerenciarEquipamento" asp-action="DeletarConfirmacao">Deletar</a>
                                <a role="button" class="btn btn-warning" asp-route-id="@equipamento.Id" asp-controller="GerenciarEquipamento" asp-action="Editar">Editar</a>
                            </div>
                        </td>
                    </tr>

                }

            }
        </tbody>
    </table>

</div>

<style>
    .close-alert {
        position: absolute;
        right: -10px;
        top: -15px;
        border-radius: 15px;
        width: 30px;
        height: 31px;
    }
</style>