UvaFit/Controllers/GerenciarTreinoController.cs
using Microsoft.AspNetCore.Mvc;
using UvaFit.Models;
using UvaFit.Repositorio;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace UvaFit.Controllers
{
    public class GerenciarTreinoController : Controller
    {

        private readonly ITreinoRepositorio _treinoRepositorio;


        public GerenciarTreinoController(ITreinoRepositorio treinoRepositorio)
        {
            _treinoRepositorio = treinoRepositorio;
        }
        public IActionResult Index()
        {
            List<TreinoModel> treinos = _treinoRepositorio.BuscarTodos();
            return View(treinos);
        }

        public IActionResult TreinoAlunoIndex()
        {
            List<TreinoModel> treinos = _treinoRepositorio.BuscarTodos();
            return View(treinos);
        }


        public IActionResult Adicionar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            TreinoModel treino = _treinoRepositorio.ListarPorId(id);
            return View(treino);
        }

        public IActionResult DeletarConfirmacao(int id)
        {
            TreinoModel treino = _treinoRepositorio.ListarPorId(id);
            return View(treino);
        }

        public IActionResult Deletar(int id)
        {
            try
            {
                bool deletado = _treinoRepositorio.Deletar(id);

                if (deletado)
                {
                    TempData["MensagemSucesso"] = "Treino deletado com sucesso";
                }
                else
                {
                    TempData["MensagemErro"] = "Não foi possível deletar o treino";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {

                TempData["MensagemErro"] = $"Não foi possível apagar o treino! Detalhe do erro: {erro.Message} ";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Adicionar(TreinoModel treinol)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _treinoRepositorio.Adicionar(treinol);
                    TempData["MensagemSucesso"] = "Treino adicionado com sucesso";
                    return RedirectToAction("Index");

                }

                return View(treinol);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Não foi possível adicionar o treino! Detalhe do erro: {erro.Message} ";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Editar(TreinoModel treinol)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _treinoRepositorio.Atualizar(treinol);
                    TempData["MensagemSucesso"] = "Treino editado com sucesso";
                    return RedirectToAction("Index");

                }

                return View(treinol);
            }
            catch (System.Exception erro)
            {

                TempData["MensagemErro"] = $"Não foi possível editar o treino! Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

UvaFit/Controllers/TelaAlunoController.cs
using Microsoft.AspNetCore.Mvc;

namespace UvaFit.Controllers
{
    public class TelaAlunoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Visualizar()
        {
            return View();
        }

        public IActionResult Treino()
        {
            return View();
        }
    }
}

UvaFit/Controllers/TelaFuncionarioController.cs
using Microsoft.AspNetCore.Mvc;

namespace UvaFit.Controllers
{
    public class TelaFuncionarioController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

UvaFit/Views/GerenciarTreino/Adicionar.cshtml
@using UvaFit.Enums
@model TreinoModel
@{
    ViewData["Title"] = "Adicionar Treino";
}

<div class="text-center">


    <h1>Adicionar Treino</h1>

</div>

<form asp-controller="GerenciarTreino" asp-action="Adicionar" method="post">
    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do aluno">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="CPF">CPF</label>
        <input type="text" asp-for="CPF" class="form-control" placeholder="Digite o CPF do aluno">
        @Html.ValidationMessageFor(x => x.CPF)
    </div>

    <div class="form-group">
        <label for="Treino">Treino</label>
        <input type="text" asp-for="Treino" class="form-control" placeholder="Digite o treino do aluno">
        @Html.ValidationMessageFor(x => x.Treino)
    </div>

    <br />

    <button type="submit" class="btn btn-success">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="GerenciarTreino" asp-action="Index" role="button">Voltar</a>

</form>

<style>
    .field-validation-error {
        color: #e01d1d;
    }
</style>

UvaFit/Views/GerenciarTreino/DeletarConfirmacao.cshtml
@model TreinoModel
@{
    ViewData["Title"] = "Deletar Treino";
}

<div class="text-center">
    <h3>Deseja realmente deletar o treino de @Model.Nome?</h3>
</div>

<div class="text-center">
    <a class="btn btn-success" role="button" asp-controller="GerenciarTreino" asp-action="Index">Cancelar</a>
    <a class="btn btn-danger" role="button" asp-controller="GerenciarTreino" asp-action="Deletar" asp-route-id="@Model.Id">Confirmar</a>
</div>

UvaFit/Views/GerenciarTreino/Editar.cshtml
@using UvaFit.Enums
@model TreinoModel
@{
    ViewData["Title"] = "Editar Treino";
}

<div class="text-center">


    <h1>Adicionar Treino</h1>

</div>

<form asp-controller="GerenciarTreino" asp-action="Adicionar" method="post">
    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do aluno">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="CPF">CPF</label>
        <input type="text" asp-for="CPF" class="form-control" placeholder="Digite o CPF do aluno">
        @Html.ValidationMessageFor(x => x.CPF)
    </div>

    <div class="form-group">
        <label for="Treino">Treino</label>
        <input type="text" asp-for="Treino" class="form-control" placeholder="Digite o treino do aluno">
        @Html.ValidationMessageFor(x => x.Treino)
    </div>

    <br />

    <button type="submit" class="btn btn-success">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="GerenciarTreino" asp-action="Index" role="button">Voltar</a>

</form>

<style>
    .field-validation-error {
        color: #e01d1d;
    }
</style>

UvaFit/Views/GerenciarTreino/Index.cshtml
@model List<TreinoModel>
@{
    ViewData["Title"] = "Gerenciar Treino";
}

<div class="text-center">

    <div class="d-flex justify-content-between">
        <a class="btn btn-success" role="button" asp-controller="GerenciarTreino" asp-action="Adicionar">Adicionar novo treino</a>
        <a class="btn btn-danger" role="button" asp-controller="TelaFuncionario" asp-action="Index">Voltar</a>
    </div>





    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"];
        </div>
    }


    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemErro"];
        </div>
    }

    <h1>Listagem de Treinos</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">CPF</th>
                <th scope="col">Treino</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (TreinoModel treino in Model)
                {
                    <tr>
                        <th scope="row">@treino.Id</th>
                        <td>@treino.Nome</td>
                        <td>@treino.CPF</td>
                        <td>@treino.Treino</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-danger" asp-route-id="@treino.Id" asp-controller="GerenciarTreino" asp-action="DeletarConfirmacao">Deletar</a>
                                <a role="button" class="btn btn-warning" asp-route-id="@treino.Id" asp-controller="GerenciarTreino" asp-action="Editar">Editar</a>
                            </div>
                        </td>
                    </tr>

                }

            }
        </tbody>
    </table>

</div>

<style>
    .close-alert {
        position: absolute;
        right: -10px;
        top: -15px;
        border-radius: 15px;
        width: 30px;
        height: 31px;
    }
</style>

UvaFit/Views/GerenciarTreino/TreinoAlunoIndex.cshtml
@model List<TreinoModel>
@{
    ViewData["Title"] = "Visualizar Treino";
}

<div class="text-center">

    <div class="d-flex justify-content-between">
        <a class="btn btn-danger" role="button" asp-controller="TelaAluno" asp-action="Index">Voltar</a>
    </div>





    <br />



    <h1>Listagem de Treinos</h1>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">CPF</th>
                <th scope="col">Treino</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (TreinoModel treino in Model)
                {
                    <tr>
                        <th scope="row">@treino.Id</th>
                        <td>@treino.Nome</td>
                        <td>@treino.CPF</td>
                        <td>@treino.Treino</td>
                        <td>
                        </td>
                    </tr>

                }

            }
        </tbody>
    </table>

</div>

<style>
    .close-alert {
        position: absolute;
        right: -10px;
        top: -15px;
        border-radius: 15px;
        width: 30px;
        height: 31px;
    }
</style>